# Generated by Django 2.2.5 on 2019-09-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='image',
            new_name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='description',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='followers_list',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='following_list',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='headline',
        ),
        migrations.AddField(
            model_name='myuser',
            name='cover_photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='coverphoto'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('C', 'Cooker'), ('U', 'User')], default='Cooker', max_length=30),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='about'),
        ),
    ]
