# Generated by Django 2.2.5 on 2019-10-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0006_auto_20191002_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='coverphoto'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='', verbose_name='profilephoto'),
        ),
    ]
