# Generated by Django 2.2.5 on 2019-10-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0008_auto_20191013_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='', verbose_name='profilephoto'),
        ),
    ]
