# Generated by Django 2.2.5 on 2019-10-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0010_auto_20191014_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(default=True, max_length=9),
            preserve_default=False,
        ),
    ]
