# Generated by Django 2.2.5 on 2019-10-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0011_auto_20191020_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
