# Generated by Django 2.2.5 on 2019-09-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='image',
            field=models.ImageField(default=True, upload_to='meals/photo'),
            preserve_default=False,
        ),
    ]
