# Generated by Django 2.2.5 on 2019-09-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_meals_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='icon_food',
        ),
        migrations.AlterField(
            model_name='main',
            name='food_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
