# Generated by Django 2.2.5 on 2019-09-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0003_auto_20190929_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='icon_food',
            field=models.ImageField(default=True, upload_to='main_icon'),
            preserve_default=False,
        ),
    ]
