# Generated by Django 2.2.5 on 2019-09-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0007_auto_20190930_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='cropping',
        ),
        migrations.AlterField(
            model_name='meals',
            name='image',
            field=models.ImageField(upload_to='meals/photo'),
        ),
    ]
