# Generated by Django 2.2.5 on 2019-09-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0010_auto_20190930_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos_Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_page', models.ImageField(blank=True, null=True, upload_to='images')),
                ('detail_page', models.ImageField(blank=True, null=True, upload_to='images')),
                ('example_page', models.ImageField(blank=True, null=True, upload_to='images')),
                ('example1_page', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
