# Generated by Django 2.2.5 on 2019-10-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0011_photos_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
