# Generated by Django 2.2.5 on 2019-10-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0012_meals_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='copyright',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
