# Generated by Django 2.2.5 on 2019-10-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0014_texts_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts_pages',
            name='addfood_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='texts_pages',
            name='detail_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='texts_pages',
            name='example_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='texts_pages',
            name='example_page1_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
