# Generated by Django 2.2.5 on 2019-10-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0015_auto_20191001_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meals',
            options={'ordering': ['-id']},
        ),
    ]
