# Generated by Django 2.2.5 on 2019-10-31 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('default', '0017_tokenmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagramfield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_img', models.ImageField(blank=True, null=True, upload_to='media_insta')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='footer',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='instagram_img',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='gram_one_porsion',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='image',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='meals',
            name='cord_lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meals',
            name='cord_lng',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meals',
            name='delivery_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordering',
            name='delivery_type',
            field=models.CharField(choices=[('User', 'User'), ('Shef', 'Shef')], default='User', max_length=244),
        ),
        migrations.AddField(
            model_name='ordering',
            name='expire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordering',
            name='location',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordering',
            name='phone_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='delivery_type',
            field=models.CharField(choices=[('User', 'User'), ('Shef', 'Shef')], default=0, max_length=244),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('activity_type', models.IntegerField(choices=[(0, 'ReadyToCooker'), (1, 'ReadyToUser'), (2, 'Comment'), (3, 'Accept Friend request'), (4, 'Reject Friend request'), (5, 'Send you money'), (6, 'Accept your advertisement'), (7, 'Reject your advertisement')], default=0)),
                ('read', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='meals/photo')),
                ('image_token', models.CharField(blank=True, max_length=55, null=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='default.Meals')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Like'), (1, 'Unlike')], default=0)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.Meals')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=130)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.Meals')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
