# Generated by Django 2.2.5 on 2019-11-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0018_auto_20191031_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='phone_number',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
    ]
