# Generated by Django 2.2.5 on 2019-11-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0020_auto_20191101_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='phone_number',
            field=models.IntegerField(default=0, max_length=9),
            preserve_default=False,
        ),
    ]
