# Generated by Django 2.2.5 on 2019-11-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0022_auto_20191101_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('User', 'User'), ('Shef', 'Shef')], default=0, max_length=244, null=True),
        ),
    ]
