# Generated by Django 2.2.5 on 2019-11-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0028_auto_20191101_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='activity_type',
            field=models.IntegerField(choices=[(0, 'ReadyToCooker'), (1, 'ReadyToUser'), (2, 'Delete'), (3, 'Accept Friend request'), (4, 'Reject Friend request'), (5, 'Send you money'), (6, 'Accept your advertisement'), (7, 'Reject your advertisement')], default=0),
        ),
    ]
