# Generated by Django 2.2.5 on 2019-11-04 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('default', '0029_auto_20191101_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordering',
            name='author_of_meal',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_of_meal', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordering',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
