# Generated by Django 2.2.5 on 2019-11-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0031_meals_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealsimages',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='meals/photo'),
        ),
    ]
