# Generated by Django 2.2.5 on 2019-11-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0032_auto_20191108_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='image_default',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
