# Generated by Django 2.2.7 on 2019-11-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0033_meals_image_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
