# Generated by Django 2.2.7 on 2019-11-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0035_auto_20191112_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
